### ISSUE TITLE
FindSql recipe null pointer exception

### ISSUE THREAD

**Issue by natedanner** [openrewrite/rewrite-sql#6]
## What version of OpenRewrite are you using?
Group: org.openrewrite.recipe
artifact: rewrite-sql
version: 1.1.0-SNAPSHOT
datedSnapshot: 1.1.0-20230820.181705-87

## How are you running OpenRewrite?
Through the Moderne SaaS
https://app.moderne.io/recipes/org.openrewrite.sql.FindSql?organizationId=RGVmYXVsdA%3D%3D

Can you share your configuration so that we can rule out any configuration issues?
N/A

Is your project public? If so, can you share a link to it?
https://github.com/spring-projects/spring-data-relational

## What is the smallest, simplest way to reproduce the problem?
Run the FindSql recipe on the https://github.com/spring-projects/spring-data-relational repo. 

## What did you expect to see?
A result without error. 

## What did you see instead?
![Screenshot 2023-08-22 at 10 49 33 AM](https://github.com/openrewrite/rewrite-sql/assets/882752/1a7b166d-05ce-4dd7-a5fc-163ccea69459)

## What is the full stack trace of any errors you encountered?
java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because the return value of "net.sf.jsqlparser.expression.AnalyticExpression.getOrderByElements()" is null
  net.sf.jsqlparser.expression.ExpressionVisitorAdapter.visit(ExpressionVisitorAdapter.java:342)
  net.sf.jsqlparser.expression.AnalyticExpression.accept(AnalyticExpression.java:73)
  net.sf.jsqlparser.expression.ExpressionVisitorAdapter.visit(ExpressionVisitorAdapter.java:523)
  net.sf.jsqlparser.statement.select.SelectExpressionItem.accept(SelectExpressionItem.java:46)
  org.openrewrite.sql.SqlDetector$1$1.visit(SqlDetector.java:79)
  net.sf.jsqlparser.statement.select.PlainSelect.accept(PlainSelect.java:145)
  org.openrewrite.sql.SqlDetector$1.visit(SqlDetector.java:72)
  net.sf.jsqlparser.statement.select.Select.accept(Select.java:30)
  ...

## Are you interested in [contributing a fix to OpenRewrite]
N/A

**Comment by timtebeek** [comment]
Working just fine now
![image](https://github.com/openrewrite/rewrite-sql/assets/1027334/4c75770a-5d8a-4a39-bd25-976f31a66d4a)

https://app.moderne.io/results/Z6NDTY5nt/details/eyJfX3R5cGVuYW1lIjoiR2l0SHViUmVwb3NpdG9yeSIsIm9yaWdpbiI6ImdpdGh1Yi5jb20iLCJwYXRoIjoic3ByaW5nLXByb2plY3RzL3NwcmluZy1kYXRhLXJlbGF0aW9uYWwiLCJicmFuY2giOiJtYWluIn0=?referrer=%2Fresults%2FZ6NDTY5nt
